# Generated by Django 6.1.1 on 2026-10-08 00:55

import apps.profiles.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userconfig'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.profiles.models.user.UserManager()),
            ],
        ),
    ]
