# Generated by Django 6.1 on 2026-09-17 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactions', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('dislike', 'Dislike'), ('angry', 'Angry')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='facebook.post')),
                ('user_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='facebook.user')),
            ],
        ),
    ]
