# Generated by Django 6.1 on 2026-09-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='reactions',
            new_name='reaction',
        ),
    ]
