# Generated by Django 6.1 on 2026-09-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_rename_reactions_like_reaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('liked_post', 'user_like'), name='unique_like_by_user'),
        ),
    ]
