# Generated by Django 6.1 on 2026-09-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('shirt_sizes', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('country', models.CharField(choices=[('PE', 'Perú'), ('CO', 'Colombia'), ('CL', 'Chile'), ('BR', 'Brasil'), ('AR', 'Argentina')], max_length=2)),
            ],
        ),
    ]
