# Generated by Django 6.1 on 2026-09-07 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_person_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=5)),
                ('continent', models.CharField(max_length=200)),
                ('independence_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(model_name='person', name='country'),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.country'),
        ),
    ]
