# Generated by Django 6.1 on 2026-09-11 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_group_membership_group_members_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'get_latest_by': 'name', 'ordering': ['name'], 'verbose_name_plural': 'people'},
        ),
        migrations.AddField(
            model_name='person',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group', through='playground.Membership', to='playground.person'),
        ),
    ]
