# Generated by Django 6.1 on 2026-09-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_country_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'get_latest_by': 'date_added', 'ordering': ['name'], 'verbose_name_plural': 'people'},
        ),
    ]
