# Generated by Django 6.1.1 on 2026-10-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_alter_postlike_user_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
    ]
