# Generated by Django 6.1.1 on 2026-10-05 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0008_comment_commentlike_comment_unique_comment_by_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_comment_by_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_comment',
            new_name='post',
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_comment_by_user'),
        ),
    ]
