# Generated by Django 6.1.1 on 2026-10-08 00:55

import apps.facebook.models.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0009_remove_comment_unique_comment_by_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.facebook.models.common.content_image_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.facebook.models.common.content_image_path, verbose_name='Imagen'),
        ),
    ]
